# Generated by Django 4.1.1 on 2024-01-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="image",
            field=models.ImageField(blank=True, upload_to="contacts"),
        ),
    ]
