"""
    Module name :- 0002_alter_contact_image
"""

# Generated by Django 4.1.1 on 2024-01-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration for data model (version 0002).
    """

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="image",
            field=models.ImageField(blank=True, upload_to="contacts"),
        ),
    ]
