"""
    Module name :- 0003_contact_starred
"""

# Generated by Django 4.1.1 on 2024-01-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration for data model (version 0003).
    """

    dependencies = [
        ("book", "0002_alter_contact_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="starred",
            field=models.BooleanField(default=False),
        ),
    ]
